image: node:18.17.1

# Helper method for angular dependencies
.shared_hidden_key: &install-angular-dependencies # This is a YAML anchor
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - npm install

production-build:
  stage: build
  <<: *install-angular-dependencies
  script:
    - apt install libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libcups2 libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libasound2-dev -qy
    - npm run build
  artifacts:
    paths:
      - dist

unit-testing:
  stage: test
  <<: *install-angular-dependencies
  script:
    - apt install libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libcups2 libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libasound2-dev -qy
    - npm run test-report-generate

pages:
  stage: deploy
  environment:
    name: production
  dependencies:
    - unit-testing
    - production-build
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - apt install gzip brotli -qy
  script:
    - mv dist/static public
    - cd public
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec gzip -k --best {} \; # gzip compress all files
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec brotli -k {} \; #Brotli compress all files
  artifacts:
    paths:
      - public
  only:
    - main
