variables:
  JEKYLL_ENV: production

# Build
build-site:
  image: ruby:2.5.1
  stage: build
  script:
  - apt-get update -y
  - apt-get install -y openjdk-7-jre-headless
  - apt-get install -y locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public

# Deploy
pages:
  image: debian:latest
  stage: deploy
  environment:
    name: production
    url: http://www.lukekuenneke.com
  dependencies:
    - build-site
  before_script:
  - apt-get update -qy
  - apt-get install brotli -qy
  script:
    - cd public
    - find . -type f \( -iname "**" ! -iname "*.gz" ! -iname "*.br" \) -exec gzip -k -8 {} \; # gzip compress all files
    - find . -type f \( -iname "**" ! -iname "*.gz" ! -iname "*.br" \) -exec brotli --input {} --force --output {}.br \; #Brotli compress all files
  artifacts:
    paths:
      - public
  only:
    - master
