image: node:16.13.1

# Cache dependencies between builds
cache:
  key: "$CI_JOB_NAME---$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

# Helper method for angular dependencies
.shared_hidden_key: &install-angular-dependencies # This is a YAML anchor
  before_script:
    - apt-get update -qy
    - npm install

# Unit Testing
unit-testing:
  <<: *install-angular-dependencies
  script:
    - npm run test-report-generate

# Production Build
production-build:
  <<: *install-angular-dependencies
  script:
    - npm run build
  artifacts:
    paths:
      - public

# Deploy
pages:
  stage: deploy
  environment:
    name: production
  dependencies:
    - unit-testing
    - production-build
  before_script:
    - apt-get update -qy
    - apt-get install brotli -qy
  script:
    - mv dist/lukekuenneke.com public
    - cd public
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec gzip -k --best {} \; # gzip compress all files
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec brotli -k {} \; #Brotli compress all files
  artifacts:
    paths:
      - public
  only:
    - main
