image: node:20.17.0

# Helper method for angular dependencies
.shared_hidden_key: &install-angular-dependencies # This is a YAML anchor
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - npm install --force

production-build:
  stage: build
  <<: *install-angular-dependencies
  script:
    - apt install libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libcups2 libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libasound2-dev -qy
    - npm run build
  artifacts:
    paths:
      - dist

unit-testing:
  stage: test
  needs: []
  <<: *install-angular-dependencies
  script:
    - apt install libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libcups2 libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libasound2-dev -qy
    - npm run test-report-generate

compress-images:
  stage: build
  image:
    name: 343dev/optimizt:8.0.1
    entrypoint: [""]
  needs: [production-build]
  script:
    - find . -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.gif -o -iname \*.svg \) -exec optimizt {} +
    - optimizt --avif .
    - optimizt --webp .
  artifacts:
    paths:
      - dist
  only:
    - main

compress-files:
  stage: build
  needs: [compress-images]
  dependencies:
    - compress-images
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - apt install gzip brotli -qy
  script:
    - cd dist
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec gzip -k --best {} \; # gzip compress all files
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec brotli -k {} \; #Brotli compress all files
  artifacts:
    paths:
      - dist
  only:
    - main

pages:
  stage: deploy
  environment:
    name: production
  needs: [compress-files]
  dependencies:
    - compress-files
  before_script:
    - apt update -qy
    - apt upgrade -qy
  script:
    - mv dist/static public
  artifacts:
    paths:
      - public
  only:
    - main
