.image-nodejs: &image-nodejs
  image: node:22.14.0

.image-debian: &image-debian
  image: library/debian:12-slim
  before_script:
    - apt update -qy
    - apt upgrade -qy

.image-optimizt: &image-optimizt
  image:
    name: 343dev/optimizt:latest
    entrypoint: [""]

.install-angular-dependencies: &install-angular-dependencies
  before_script:
    - apt update -qy
    - apt upgrade -qy
    - apt install libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libcups2 libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libasound2-dev -qy
    - npm install

production-build:
  stage: build
  <<: [*image-nodejs, *install-angular-dependencies]
  script:
    - npm run build
  artifacts:
    paths:
      - dist

compress-images:
  stage: build
  <<: [*image-optimizt]
  needs: [production-build]
  script:
    - find . -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.gif -o -iname \*.svg \) -exec optimizt {} +
    - optimizt --avif .
    - optimizt --webp .
  artifacts:
    paths:
      - dist
  only:
    - main

compress-files:
  stage: build
  <<: [*image-debian]
  needs: [compress-images]
  dependencies:
    - compress-images
  script:
    - apt install gzip brotli -qy
    - cd dist
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec gzip -k --best {} \; # gzip compress all files
    - find . -type f \( -iname "*.*" ! -iname "*.gz" ! -iname "*.br" \) -exec brotli -k {} \; #Brotli compress all files
  artifacts:
    paths:
      - dist
  only:
    - main

pages:
  stage: deploy
  <<: [*image-debian]
  environment:
    name: production
  needs: [compress-files]
  dependencies:
    - compress-files
  script:
    - mv dist/lukekuenneke.com/browser public
  artifacts:
    paths:
      - public
  only:
    - main
